fix: trigger doc build all condition (#2242)
* fix: trigger doc build all condition

* test-ci-fix: try not reset daalroot in doc.yml

* test-ci-fix: revert dalroot set in doc.yml

* temp: print statements to pipline to see the sys path behavior

* fix: add sklearn and daal4py folder to sys path

* fix: revert change to conf.py

* fix: confirm change needed in conf.py

* fix: import daal4py and sklearn to path in conf.py for both daal4py and sklearn doc build

* ci-print: remove useless print in doc.yml and sys.path import to avoid circular import

* test-ci: additional print

* fix: import build .so file

* fix: update intelex to include build dir as well

* fix: import build only test

* fix: test need the lib folder

* fix: test add one dal to dep

* fix: remove unused env var

* fix: fix syntax

* test-fix: cp so to intel64 folder

* fix: cp so file

* fix: add ld libraryu path

* fix: export ld lib path

* test: remove the cp to intel64 step

* test: remove the cp to intel64 step

* fix: removed prints

* fix: build doc instead make html

* fix: add permisson for build doc.sh

* fix: add pakcagte install

* feature: new rule in make to mark autodoc warnings as erros

* fix: also print the logs at end

* fix: rever the env variables

* fix: change main make rule instread adding a new rule

* fix: comnine apt get and remove useless source command

* fix: move warning detect from makefile to build-doc.sh and yml

* fix: fix exclude command to not include daal4py_data_science.ipynb when copy

* fix: use --inplace flag for setup.py isntead

* fix: remove cp command

* fix: remove build.sh

* fix: add build.sh back

* fix: empty lines at end replace build.sh with another setup.py

* fix: change make command in build-doc.sh

* fix: remove cd doc to avoid daal4py import mistakenly from doc

* fix: use build.sh to pritiorize sitepckage daal4py

* fix: test fix with removing conf sys path add

* ci-test: test daal4py import fail warning would cause error in pipeline

* fix: revert branch

* fix: revert make file

* fix: remove unneccesry delete of line
---------

Co-authored-by: yue.jiao <yuejiao@smtp.intel.com>
Co-authored-by: yuejiaointel <yue.jiao@gmail.com>

diff --git a/.ci/pipeline/docs.yml b/.ci/pipeline/docs.yml
--- a/.ci/pipeline/docs.yml
+++ b/.ci/pipeline/docs.yml
@@ -54,7 +54,7 @@ jobs:
     inputs:
       versionSpec: '3.11'
       addToPath: true
-  - script: sudo apt-get update && sudo apt-get install -y clang-format
+  - script: sudo apt-get update && sudo apt-get install -y clang-format pandoc 
     displayName: 'apt-get'
   - script: |
       pip install daal-devel impi-devel
@@ -64,18 +64,25 @@ jobs:
       pip list
     displayName: 'Install requirements'
   - script: |
-      export PREFIX=$(dirname $(dirname $(which python)))
-      export DALROOT=$PREFIX
+      export DALROOT=$(dirname $(dirname $(which python)))
+      export LD_LIBRARY_PATH=$(dirname $(dirname $(which python)))/lib:$LD_LIBRARY_PATH
       ./conda-recipe/build.sh
     displayName: 'Build daal4py/sklearnex'
   - script: |
       export LD_LIBRARY_PATH=$(dirname $(dirname $(which python)))/lib:$LD_LIBRARY_PATH
       cd doc/daal4py
-      make html
+      make html 2>&1 | tee build.log
+      cat build.log
+      # check for autodoc warnings
+      if grep -i "autodoc" build.log; then
+        echo "Autodoc Warnings detected, build failed!"
+        exit 1
+      fi
     displayName: 'Build daal4py documentation'
   - script: |
+      export LD_LIBRARY_PATH=$(dirname $(dirname $(which python)))/lib:$LD_LIBRARY_PATH
       cd doc
-      make html
+      ./build-doc.sh
     displayName: 'Build scikit-learn-intelex documentation'
   - script: |
       mkdir $(Build.ArtifactStagingDirectory)/html/daal4py
